<a href="https://colab.research.google.com/github/surimajain/QuantAnalytics/blob/main/PCA_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principal Component Analysis


# Need for PCA

PCA is required to reduce the curse of dimensions in data and reduce the overfitiing of the data in the model. High dimension data is extremely complex process due to inconsistency in the features which increases the computation time and make the processing of data and EDA more convoluted.

![download.png](attachment:download.png)

# What is PCA ??

Principal Component Analysis is a dimensionality reduction technique that enables you to identify corelations and patterns in a data set so that it can be transformed into a data set of significantly lower dimension without loss of any important information.

Steps in PCA:

- 1) Standardization of the Data 
- 2) Computing the Covariance Matrix
- 3) Calculating the Eigenvectors and Eigenvalues
- 4) Computing the Principal Components
- 5) Reducing the dimensions of the data 

# Eigenvectors and Eigenvalues

- Eigenvectors and Eigenvalues are the mathematical constructs that must be computed from the covariance matrix in order to determine the principal components of the dataset.

- Eigenvectors are those vectors when a linear transformation is performed on them then their direction does not change.

- Eigenvalues simply denote the scalar of the respective eigenvectors

- Principal Components are the new set of variables that are obtained from the initial set of variables. They compress and possess most of the useful information that was scattered among the initial variables.



# Computing the Principal Components

Once we have computed the eigen vectors and eigen values , we have to order them in a descending order where the eigen vector with the highest eigen value is the most significant and thus forms the first principal component.

- PC1 is the most significant and stores the maximum value possible
- PC2 is the second most significant and stores the remaining maximum info and so on.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/sample_data/PCA.csv")
df

FileNotFoundError: ignored

In [ ]:
from sklearn.preprocessing import StandardScaler
features = ['x' ,'y']
# Separating out the features
x = df.loc[:, features].values
# Standardizing the features
x = StandardScaler().fit_transform(x)

In [ ]:
x

array([[ 0.92627881,  0.61016865],
       [-1.7585873 , -1.506743  ],
       [ 0.52354889,  1.23278973],
       [ 0.12081898,  0.36112022],
       [ 1.73173864,  1.35731394],
       [ 0.6577922 ,  0.9837413 ],
       [ 0.25506228, -0.38602507],
       [-1.08737078, -1.00864614],
       [-0.41615425, -0.38602507],
       [-0.95312747, -1.25769457]])

In [ ]:
cov_matrix = df.cov()

In [ ]:
cov_matrix

x         y
x  0.616556  0.615444
y  0.615444  0.716556

In [ ]:
print()

In [ ]:
# Perform eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
# Put data into a DataFrame
#df_eigval = pd({"Eigenvalues":eigenvalues}, index=range(1,21))
print(eigenvalues)
print(eigenvectors)

NameError: ignored

In [ ]:
principal_components = x.dot(eigenvectors)
principal_components

array([[-0.26736331, -1.07648273],
       [ 0.27149485,  2.29982484],
       [ 0.45077339, -1.26122056],
       [ 0.15597026, -0.34738785],
       [-0.35305027, -2.1717678 ],
       [ 0.18325727, -1.16912544],
       [-0.44919247,  0.11089745],
       [ 0.1156774 ,  1.47863484],
       [ 0.0442716 ,  0.56589728],
       [-0.15183872,  1.57072996]])

In [ ]:
# eig_vals, eig_vecs = np.linalg.eig(cov_mat)
eig_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:,i]) for i in range(len(eigenvalues))]
eig_pairs.sort()
eig_pairs.reverse()
pc1 = eig_pairs[0][1]
pc1 = pd.DataFrame(pc1)
pc1


NameError: ignored

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [ ]:
principalDf

principal component 1  principal component 2
0              -1.086432              -0.223524
1               2.308937               0.178081
2              -1.241919               0.501509
3              -0.340782               0.169919
4              -2.184290              -0.264758
5              -1.160739               0.230481
6               0.092605              -0.453317
7               1.482108               0.055667
8               0.567226               0.021305
9               1.563287              -0.215361

#PCA of yield curve

In [73]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np# Import Bank of England spot curve data from excel
df = pd.read_excel("/content/sample_data/GLC Nominal daily data current month.xlsx", 
                   index_col=0, header=3,  sheet_name="4. spot curve", skiprows=[4])
# df=pd.read_csv("/content/sample_data/PCA.csv")
# Select all of the data up to 10 years
df = df.iloc[:,0:10]
df.head()

0.5       1.0       1.5  ...       4.0       4.5       5.0
years:                                    ...                              
2021-02-01 -0.133517 -0.111626 -0.102026  ... -0.042472 -0.018699  0.008595
2021-02-02 -0.129386 -0.098325 -0.084978  ... -0.020367  0.004023  0.031928
2021-02-03 -0.118508 -0.091671 -0.078094  ... -0.005745  0.019505  0.048093
2021-02-04 -0.069287 -0.041651 -0.028050  ...  0.048950  0.076006  0.106421
2021-02-05 -0.061380 -0.034100 -0.016956  ...  0.080579  0.110700  0.143910

[5 rows x 10 columns]

#Standardize Data


In [75]:
from sklearn.preprocessing import StandardScaler
# features = ['0.5' ,'1.0']
# Separating out the features
X = df.values
X#-0.13351706, -0.11162642, -0.10202635, -0.09610075, -0.08868899
# Standardizing the features
x = StandardScaler().fit_transform(X)
x#-2.60795527e+00, -2.41323673e+00, -2.16613962e+00,        -2.03878006e+00, -1.95087877e+00

array([[-2.60795527e+00, -2.41323673e+00, -2.16613962e+00,
        -2.03878006e+00, -1.95087877e+00, -1.88196569e+00,
        -1.82684898e+00, -1.78282215e+00, -1.74780276e+00,
        -1.72011524e+00],
       [-2.43137693e+00, -1.88926638e+00, -1.64197987e+00,
        -1.58146054e+00, -1.55790623e+00, -1.53992640e+00,
        -1.52333399e+00, -1.50823521e+00, -1.49501621e+00,
        -1.48385702e+00],
       [-1.96636397e+00, -1.62714493e+00, -1.43034471e+00,
        -1.37004842e+00, -1.34911085e+00, -1.33870471e+00,
        -1.33176941e+00, -1.32660263e+00, -1.32278135e+00,
        -1.32017381e+00],
       [ 1.37681131e-01,  3.43322394e-01,  1.08280853e-01,
        -1.57438931e-01, -3.54828693e-01, -4.89974251e-01,
        -5.82392446e-01, -6.47191309e-01, -6.94191219e-01,
        -7.29567634e-01],
       [ 4.75667559e-01,  6.40775444e-01,  4.49349868e-01,
         2.25977118e-01,  4.63409368e-02, -8.62727486e-02,
        -1.82927885e-01, -2.54307197e-01, -3.08212824e-01,
        -3.

#Calculate Correlation Matrix

In [76]:
corr_matrix=df.corr()
corr_matrix

0.5       1.0       1.5  ...       4.0       4.5       5.0
0.5  1.000000  0.904239  0.827522  ...  0.733419  0.723288  0.714936
1.0  0.904239  1.000000  0.980702  ...  0.835977  0.816932  0.800956
1.5  0.827522  0.980702  1.000000  ...  0.900693  0.883324  0.868400
2.0  0.796784  0.950137  0.989910  ...  0.950962  0.937963  0.926396
2.5  0.776729  0.916883  0.968119  ...  0.979550  0.970694  0.962386
3.0  0.759958  0.885753  0.943718  ...  0.993206  0.987702  0.982060
3.5  0.745576  0.858741  0.920838  ...  0.998700  0.995819  0.992281
4.0  0.733419  0.835977  0.900693  ...  1.000000  0.999179  0.997303
4.5  0.723288  0.816932  0.883324  ...  0.999179  1.000000  0.999457
5.0  0.714936  0.800956  0.868400  ...  0.997303  0.999457  1.000000

[10 rows x 10 columns]

In [80]:
eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
print(eigenvectors)
# Put data into a DataFrame
df_eigval = pd.DataFrame({"Eigenvalues":eigenvalues})

# Work out explained proportion 
df_eigval["Explained proportion"] = df_eigval["Eigenvalues"] / np.sum(df_eigval["Eigenvalues"])#Format as percentage
df_eigval.style.format({"Explained proportion": "{:.2%}"})

[[-2.71479753e-01 -6.45687462e-01  6.61004087e-01  2.39286383e-01
   1.17644870e-01 -3.62914294e-02  6.23862592e-03  2.39280702e-03
   1.99241557e-04 -1.03930088e-06]
 [-3.05653345e-01 -4.63218754e-01 -2.69460796e-01 -5.83270696e-01
  -4.75765596e-01  2.19298905e-01 -6.27917470e-02 -2.81977514e-02
  -2.78494853e-03 -9.21799514e-05]
 [-3.17738956e-01 -2.30205395e-01 -4.44936590e-01 -7.82496202e-02
   4.72185575e-01 -5.57266388e-01  2.76922745e-01  1.76016927e-01
   2.78496069e-02  2.65514566e-03]
 [-3.25222219e-01 -5.75990258e-02 -3.31618431e-01  2.96802217e-01
   3.23854130e-01  3.11563077e-01 -4.56439246e-01 -5.08412985e-01
  -1.52854424e-01 -2.66917792e-02]
 [-3.27532299e-01  6.36505602e-02 -1.78342747e-01  3.85914105e-01
  -8.15378717e-02  3.92675080e-01  1.34097642e-02  5.82710226e-01
   4.35129304e-01  1.34256151e-01]
 [-3.26769182e-01  1.48404013e-01 -4.43712077e-02  3.04255668e-01
  -3.19722034e-01  3.78302302e-02  4.27022339e-01  3.18470719e-02
  -5.89002639e-01 -3.77780648e-01

In [78]:
principal_components = x.dot(eigenvectors)
principal_components

array([[ 6.32295067e+00,  1.14708212e+00, -2.35116675e-01,
         1.67763212e-02,  4.78048562e-03, -2.48085754e-03,
         8.36680672e-05,  5.81312667e-05,  6.21758274e-06,
         5.36755356e-07],
       [ 5.21631655e+00,  9.97737413e-01, -5.49879384e-01,
        -2.98222741e-02, -3.37047896e-03,  6.22946846e-04,
         2.50024875e-04,  3.47668330e-05, -4.09637120e-06,
        -4.38662013e-07],
       [ 4.51210314e+00,  7.44435259e-01, -4.02069198e-01,
         2.24097936e-02, -2.15364764e-03,  2.29446331e-03,
        -4.67425726e-04, -9.86125030e-05, -5.19453916e-06,
        -1.88944384e-07],
       [ 1.00182124e+00, -1.06987053e+00, -3.96732097e-01,
        -7.63215843e-02, -5.76006913e-03, -9.76376778e-04,
        -3.85142238e-05,  1.01385488e-05,  1.28134224e-05,
         2.27823488e-07],
       [-1.77347955e-01, -1.02979149e+00, -3.50022824e-01,
        -2.41844864e-02, -1.63984343e-03,  1.47855755e-03,
        -3.43848653e-04, -6.87570519e-06,  9.34419759e-06,
        -6.

In [79]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])
principalDf

principal component 1  principal component 2
0               -6.322951               1.147082
1               -5.216317               0.997737
2               -4.512103               0.744435
3               -1.001821              -1.069871
4                0.177348              -1.029791
5               -0.163591              -0.937590
6               -0.768013              -1.007024
7               -0.577480              -0.835530
8               -1.178045              -0.922310
9               -0.673849              -0.657766
10              -0.114546              -0.333878
11               0.428235              -0.011566
12              -0.754441               0.074218
13               0.481127               0.238105
14               2.439719               0.372725
15               1.992649               0.531809
16               1.612684               0.696305
17               1.941524               0.836405
18               5.199435               0.550656
19               7.010435               0.615848